### ISSUE TITLE
READMEの設定の箇所に誤りがある?

### ISSUE THREAD

**Issue by shyazusa** [textlint-ja/textlint-rule-preset-ja-technical-writing#118]
こんにちは。
READMEの中の設定項目にいくつか誤りがある事に気付いたのでIssueにて報告をさせて頂きます。 🙇🏼 
PRを作ることも考えましたが、いきなりコミットルールなどに沿っていないPR出されても困るかもと思い、Issueでの報告という形を取りました。
私が気付いた誤りがありそうな箇所は以下の3つです。

1. https://github.com/textlint-ja/textlint-rule-preset-ja-technical-writing#%E6%BC%A2%E6%95%B0%E5%AD%97%E3%81%A8%E7%AE%97%E7%94%A8%E6%95%B0%E5%AD%97%E3%82%92%E4%BD%BF%E3%81%84%E5%88%86%E3%81%91%E3%81%BE%E3%81%99 の設定が `arabic-kanji-numbers` となっているが `preset-jtf-style` の誤り?
2. https://github.com/textlint-ja/textlint-rule-preset-ja-technical-writing#%E4%B8%8D%E5%BF%85%E8%A6%81%E3%81%AA%E5%88%B6%E5%BE%A1%E6%96%87%E5%AD%97%E3%82%92%E4%BD%BF%E7%94%A8%E3%81%97%E3%81%AA%E3%81%84 の設定の `no-invalid-control-character` は `@textlint-rule/no-invalid-control-character` として `@textlint-rule/` が必要そう?
3. https://github.com/textlint-ja/textlint-rule-preset-ja-technical-writing#%E5%AF%BE%E3%81%AB%E3%81%AA%E3%81%A3%E3%81%A6%E3%81%84%E3%81%AA%E3%81%84%E6%8B%AC%E5%BC%A7%E3%82%92%E3%83%81%E3%82%A7%E3%83%83%E3%82%AF%E3%81%99%E3%82%8B の設定の `no-unmatched-pair` は `@textlint-rule/no-unmatched-pair` として `@textlint-rule/` が必要そう?

最後の2つの `@textlint-rule/` が必要なものは、他にもあるかもしれません。
以上です。

もしもPRを出しちゃっても良ければ、修正させて頂きます! 🙇🏼 
どうぞよろしくお願いいたします。

**Comment by azu** [comment]
https://github.com/textlint-ja/textlint-rule-preset-ja-technical-writing/blob/28a1fe0e899ed813de6595e7b194b6bc07a54221/lib/textlint-rule-preset-ja-technical-writing.js#L6-L28
preset内のキーからは `@textlint-rule/` を取り除いているので、`@textlint-rule/` がなくても設定が反映されるはずなのですが、実際にされない感じですかね?
(textlint 13で結構変更していたので、何かしらかのバグがあるのかもしれないです)

**Comment by shyazusa** [comment]
素早い返答ありがとうございます!
あ、理解できました。
私の使い方に誤りがあって、

```
{
  "rules": {
    "preset-ja-technical-writing": {
      "hoge": false
    }
  }
}
```

と設定しないといけないところを

```
{
  "rules": {
    "hoge": false
  }
}
```

と設定しちゃっていました。 🙇🏼 
ですので `textlint-rule-preset-ja-technical-writing` のオプションとしての指定が出来ていませんでした。
失礼いたしました。 🙇🏼

**Comment by azu** [comment]
READMEを全部、完全な設定として機能するように直した方が良い気がしますね。

```json
{
  "rules": {
    "preset-ja-technical-writing": {
      "hoge": false
    }
  }
}
```

**Comment by azu** [comment]
https://github.com/textlint-ja/textlint-rule-preset-ja-technical-writing/pull/120
でREADMEを全部書き直しました

**Comment by shyazusa** [comment]
ありがとうございます!! 🙇🏼
